---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wang1.
--- DateTime: 2022/9/8 8:57
---

--1.参数列表
--1.1 优惠券id
local voucherId = ARGV[1]
--1.2 用户id
local userId = ARGV[2]

--2.数据key
--2.1库存key (字符串拼接)
local stockKey = 'seckill:stock:' .. voucherId
--2.2订单key
local orderKey = 'seckill:order:' .. voucherId

--3.脚本业务
--3.1若库存不足返回1
if( tonumber(redis.call('get',stockKey)) <= 0 ) then
    return 1
end
--3.2判断用户是否为重复下单
if(tonumber(redis.call('sismember',orderKey,userId)) == 1) then
    return 2
end

--3.3口库存
redis.call('incrby',stockKey,-1)
--3.4加订单
redis.call('sadd',orderKey,userId)
return 0